// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from 'react';
import {
  PlasmicGbrCloneTool,
  DefaultGbrCloneToolProps,
} from './plasmic/arturel/PlasmicGbrCloneTool';
import { HTMLElementRefOf } from '@plasmicapp/react-web';
import { GbrDataModel } from '../renderer/models/GbrDataModel';

export interface CloneInfo {
  cx:number
  cy:number
}
export interface GbrCloneToolProps extends DefaultGbrCloneToolProps {
  nodeData?: GbrDataModel
  cloneItems:(cloneInfo:CloneInfo)=>void
}



function GbrCloneTool_(props: GbrCloneToolProps, ref: HTMLElementRefOf<'div'>) {
  const [cloneInfo, setCloneInfo] = React.useState<CloneInfo>({
    cy:0,
    cx:0
  })


  return <PlasmicGbrCloneTool root={{ ref }} onChange={(cx, cy, px) => {
    setCloneInfo({
      cx: cx ?? cloneInfo.cx,
      cy: cy ?? cloneInfo.cy,
    })
  }} clone={()=>{
    props.cloneItems(cloneInfo);
  }} clear={()=>{
    props.clear && props.clear();
  }}/>
}

const GbrCloneTool = React.forwardRef(GbrCloneTool_);
export default GbrCloneTool;
