// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from 'react';
import {
  PlasmicGbrEditor,
  DefaultGbrEditorProps,
} from './plasmic/arturel/PlasmicGbrEditor';
import { HTMLElementRefOf } from '@plasmicapp/react-web';

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface GbrEditorProps extends Omit<DefaultGbrEditorProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultGbrEditorProps altogether and have
// total control over the props for your component.
export interface GbrEditorProps extends DefaultGbrEditorProps {}

function GbrEditor_(props: GbrEditorProps, ref: HTMLElementRefOf<'div'>) {

  return <PlasmicGbrEditor root={{ ref }} {...props}/>;
}

const GbrEditor = React.forwardRef(GbrEditor_);
export default GbrEditor;
