// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dgFPhDvLY4vKuXTDNeS2uD
// Component: yPi8m4SnU-qf

import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';
import { AntdSwitch } from '@plasmicpkgs/antd5/skinny/registerSwitch'; // plasmic-import: -gkBqPikhk/codeComponent
import { AntdButton } from '@plasmicpkgs/antd5/skinny/registerButton'; // plasmic-import: bx9Xzvf5_eu/codeComponent

import '@plasmicapp/react-web/lib/plasmic.css';

import plasmic_antd_5_hostless_css from '../antd_5_hostless/plasmic_antd_5_hostless.module.css'; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from './plasmic_arturel.module.css'; // plasmic-import: dgFPhDvLY4vKuXTDNeS2uD/projectcss
import sty from './PlasmicGbrToolPathTool.module.css'; // plasmic-import: yPi8m4SnU-qf/css

createPlasmicElementProxy;

export type PlasmicGbrToolPathTool__VariantMembers = {};
export type PlasmicGbrToolPathTool__VariantsArgs = {};
type VariantPropType = keyof PlasmicGbrToolPathTool__VariantsArgs;
export const PlasmicGbrToolPathTool__VariantProps =
  new Array<VariantPropType>();

export type PlasmicGbrToolPathTool__ArgsType = {
  toolPathModeChanged?: (toolPathMode: boolean) => void;
  generateToolPath?: () => void;
};
type ArgPropType = keyof PlasmicGbrToolPathTool__ArgsType;
export const PlasmicGbrToolPathTool__ArgProps = new Array<ArgPropType>(
  'toolPathModeChanged',
  'generateToolPath'
);

export type PlasmicGbrToolPathTool__OverridesType = {
  root?: p.Flex<'div'>;
  toolPathMode?: p.Flex<typeof AntdSwitch>;
  button?: p.Flex<typeof AntdButton>;
};

export interface DefaultGbrToolPathToolProps {
  toolPathModeChanged?: (toolPathMode: boolean) => void;
  generateToolPath?: () => void;
  className?: string;
}

const $$ = {};

function PlasmicGbrToolPathTool__RenderFunc(props: {
  variants: PlasmicGbrToolPathTool__VariantsArgs;
  args: PlasmicGbrToolPathTool__ArgsType;
  overrides: PlasmicGbrToolPathTool__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants,
  };

  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof p.useDollarState>[0] = React.useMemo(
    () => [
      {
        path: 'toolPathMode.checked',
        type: 'private',
        variableType: 'boolean',
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
      },
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs,
  });

  return (
    <div
      data-plasmic-name={'root'}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__ipg69)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__yfwg6
          )}
        >
          {'Activate Toolpath Mode'}
        </div>
        <AntdSwitch
          data-plasmic-name={'toolPathMode'}
          data-plasmic-override={overrides.toolPathMode}
          checked={p.generateStateValueProp($state, [
            'toolPathMode',
            'checked',
          ])}
          className={classNames('__wab_instance', sty.toolPathMode)}
          onChange={async (...eventArgs: any) => {
            p.generateStateOnChangeProp($state, [
              'toolPathMode',
              'checked',
            ]).apply(null, eventArgs);
            (async (checked) => {
              const $steps = {};
              $steps['runToolPathModeChanged'] = true
                ? (() => {
                    const actionArgs = {
                      eventRef: $props['toolPathModeChanged'],
                      args: [
                        (() => {
                          try {
                            return $state.toolPathMode.checked;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === 'PlasmicUndefinedDataError'
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })(),
                      ],
                    };
                    return (({ eventRef, args }) => {
                      return eventRef?.(...(args ?? []));
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                typeof $steps['runToolPathModeChanged'] === 'object' &&
                typeof $steps['runToolPathModeChanged'].then === 'function'
              ) {
                $steps['runToolPathModeChanged'] = await $steps[
                  'runToolPathModeChanged'
                ];
              }
            }).apply(null, eventArgs);
          }}
        />
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__k9Mac)}>
        <AntdButton
          data-plasmic-name={'button'}
          data-plasmic-override={overrides.button}
          className={classNames('__wab_instance', sty.button)}
          disabled={(() => {
            try {
              return !$state.toolPathMode.checked;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === 'PlasmicUndefinedDataError'
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
          onClick={async () => {
            const $steps = {};
            $steps['runGenerateToolPath'] = true
              ? (() => {
                  const actionArgs = { eventRef: $props['generateToolPath'] };
                  return (({ eventRef, args }) => {
                    return eventRef?.(...(args ?? []));
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              typeof $steps['runGenerateToolPath'] === 'object' &&
              typeof $steps['runGenerateToolPath'].then === 'function'
            ) {
              $steps['runGenerateToolPath'] = await $steps[
                'runGenerateToolPath'
              ];
            }
          }}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___4Ljlg
            )}
          >
            {'generateToolPath'}
          </div>
        </AntdButton>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'toolPathMode', 'button'],
  toolPathMode: ['toolPathMode'],
  button: ['button'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  toolPathMode: typeof AntdSwitch;
  button: typeof AntdButton;
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicGbrToolPathTool__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicGbrToolPathTool__VariantsArgs;
    args?: PlasmicGbrToolPathTool__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicGbrToolPathTool__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicGbrToolPathTool__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicGbrToolPathTool__ArgProps,
          internalVariantPropNames: PlasmicGbrToolPathTool__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicGbrToolPathTool__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicGbrToolPathTool';
  } else {
    func.displayName = `PlasmicGbrToolPathTool.${nodeName}`;
  }
  return func;
}

export const PlasmicGbrToolPathTool = Object.assign(
  // Top-level PlasmicGbrToolPathTool renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    toolPathMode: makeNodeComponent('toolPathMode'),
    button: makeNodeComponent('button'),

    // Metadata about props expected for PlasmicGbrToolPathTool
    internalVariantProps: PlasmicGbrToolPathTool__VariantProps,
    internalArgProps: PlasmicGbrToolPathTool__ArgProps,
  }
);

export default PlasmicGbrToolPathTool;
/* prettier-ignore-end */
