// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dgFPhDvLY4vKuXTDNeS2uD
// Component: 9eQClZasp6EW

import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';
import { AntdButton } from '@plasmicpkgs/antd5/skinny/registerButton'; // plasmic-import: bx9Xzvf5_eu/codeComponent
import { AntdSwitch } from '@plasmicpkgs/antd5/skinny/registerSwitch'; // plasmic-import: -gkBqPikhk/codeComponent

import '@plasmicapp/react-web/lib/plasmic.css';

import plasmic_antd_5_hostless_css from '../antd_5_hostless/plasmic_antd_5_hostless.module.css'; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from './plasmic_arturel.module.css'; // plasmic-import: dgFPhDvLY4vKuXTDNeS2uD/projectcss
import sty from './PlasmicGbrViewTool.module.css'; // plasmic-import: 9eQClZasp6EW/css

createPlasmicElementProxy;

export type PlasmicGbrViewTool__VariantMembers = {};
export type PlasmicGbrViewTool__VariantsArgs = {};
type VariantPropType = keyof PlasmicGbrViewTool__VariantsArgs;
export const PlasmicGbrViewTool__VariantProps = new Array<VariantPropType>();

export type PlasmicGbrViewTool__ArgsType = {
  visibilityChange?: (showLabels: boolean) => void;
};
type ArgPropType = keyof PlasmicGbrViewTool__ArgsType;
export const PlasmicGbrViewTool__ArgProps = new Array<ArgPropType>(
  'visibilityChange'
);

export type PlasmicGbrViewTool__OverridesType = {
  root?: p.Flex<'div'>;
  button?: p.Flex<typeof AntdButton>;
  freeBox?: p.Flex<'div'>;
  _switch?: p.Flex<typeof AntdSwitch>;
};

export interface DefaultGbrViewToolProps {
  visibilityChange?: (showLabels: boolean) => void;
  className?: string;
}

const $$ = {};

function PlasmicGbrViewTool__RenderFunc(props: {
  variants: PlasmicGbrViewTool__VariantsArgs;
  args: PlasmicGbrViewTool__ArgsType;
  overrides: PlasmicGbrViewTool__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants,
  };

  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof p.useDollarState>[0] = React.useMemo(
    () => [
      {
        path: '_switch.checked',
        type: 'private',
        variableType: 'boolean',
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
      },
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs,
  });

  return (
    <div
      data-plasmic-name={'root'}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <AntdButton
        data-plasmic-name={'button'}
        data-plasmic-override={overrides.button}
        className={classNames('__wab_instance', sty.button)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__gdlxJ
          )}
        >
          {'Button'}
        </div>
      </AntdButton>
      <div
        data-plasmic-name={'freeBox'}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__ixzz
          )}
        >
          {'Show Labels'}
        </div>
        <AntdSwitch
          data-plasmic-name={'_switch'}
          data-plasmic-override={overrides._switch}
          checked={p.generateStateValueProp($state, ['_switch', 'checked'])}
          className={classNames('__wab_instance', sty._switch)}
          onChange={async (...eventArgs: any) => {
            p.generateStateOnChangeProp($state, ['_switch', 'checked']).apply(
              null,
              eventArgs
            );
            (async (checked) => {
              const $steps = {};
              $steps['runVisibilityChange'] = true
                ? (() => {
                    const actionArgs = {
                      eventRef: $props['visibilityChange'],
                      args: [
                        (() => {
                          try {
                            return $state._switch.checked;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === 'PlasmicUndefinedDataError'
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })(),
                      ],
                    };
                    return (({ eventRef, args }) => {
                      return eventRef?.(...(args ?? []));
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                typeof $steps['runVisibilityChange'] === 'object' &&
                typeof $steps['runVisibilityChange'].then === 'function'
              ) {
                $steps['runVisibilityChange'] = await $steps[
                  'runVisibilityChange'
                ];
              }
            }).apply(null, eventArgs);
          }}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'button', 'freeBox', '_switch'],
  button: ['button'],
  freeBox: ['freeBox', '_switch'],
  _switch: ['_switch'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  button: typeof AntdButton;
  freeBox: 'div';
  _switch: typeof AntdSwitch;
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicGbrViewTool__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicGbrViewTool__VariantsArgs;
    args?: PlasmicGbrViewTool__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicGbrViewTool__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicGbrViewTool__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicGbrViewTool__ArgProps,
          internalVariantPropNames: PlasmicGbrViewTool__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicGbrViewTool__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicGbrViewTool';
  } else {
    func.displayName = `PlasmicGbrViewTool.${nodeName}`;
  }
  return func;
}

export const PlasmicGbrViewTool = Object.assign(
  // Top-level PlasmicGbrViewTool renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent('button'),
    freeBox: makeNodeComponent('freeBox'),
    _switch: makeNodeComponent('_switch'),

    // Metadata about props expected for PlasmicGbrViewTool
    internalVariantProps: PlasmicGbrViewTool__VariantProps,
    internalArgProps: PlasmicGbrViewTool__ArgProps,
  }
);

export default PlasmicGbrViewTool;
/* prettier-ignore-end */
